version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql 
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: startuplab180@gmail.com 
      PGADMIN_DEFAULT_PASSWORD: Lio314271@
    ports:
      - "8080:80"  
    networks:
      - app-network 

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - app-network

  evolution-api:
    image: evoapicloud/evolution-api:latest
    container_name: evolution-api-local
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy

      redis:
        condition: service_healthy
    ports:
      - "4000:4000"  # Exposto para testes diretos
    volumes:
      - evolution_instances:/evolution/instances
    environment:
      - SERVER_TYPE=http
      - SERVER_PORT=4000
      - SERVER_URL=http://localhost:4000
      
      # Auth
      - AUTHENTICATION_TYPE=apikey
      - AUTHENTICATION_API_KEY=${EVOLUTION_API_KEY}
      - AUTHENTICATION_EXPOSE_IN_FETCH_INSTANCES=true
      
      # Database
      - DATABASE_ENABLED=true
      - DATABASE_CONNECTION_URI=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/evolution_db
      - DATABASE_CONNECTION_CLIENT_NAME=evolution-api
      - DATABASE_SAVE_DATA_INSTANCE=true
      - DATABASE_PROVIDER=postgresql

      # Cache
      - CACHE_REDIS_ENABLED=true
      - CACHE_REDIS_URI=redis://redis:6379
      - CACHE_REDIS_PREFIX_KEY=evolution
      - CACHE_LOCAL_ENABLED=false
      
      # QR Code
      - QRCODE_LIMIT=30
      - QRCODE_COLOR=#198754
      
      # Websocket
      - WEBSOCKET_ENABLED=false
      
      # Webhook Global
      - WEBHOOK_GLOBAL_ENABLED=false
      
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/code
    networks:
      - app-network
    restart: unless-stopped

volumes:
  pgdata:
  redis_data:
  evolution_instances:

networks:
  app-network:
    driver: bridge
